spring.application.name=splitManager

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/split_manager?createDatabaseIfNotExist=true

# DB credentials
spring.datasource.username=root
spring.datasource.password=root@123

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


## JWT
jwt.secret = MyNameIsAkshayAmbaliyathisisandprivatekeytocreatejwt34567token...
jwt.expiration = 86400000


server.port=8081


## Cloudinary

cloudinary.cloud-name=di0sfe6ky
cloudinary.api-key=318192888714641
cloudinary.api-secret=D1Qiytjsi8939i5U--7kcNcBqxQ